# Duration reference table:
# y = Year
# M = Month
# d = Day
# h = Hour
# m = Minute
# s = Second

cleaner:
  enable: true
  interval: 1d
  offline-allowance: 3M

logging:
  file:
    enable: true
    # relative to plugin data folder
    filename: log.txt
